# Generated by Django 4.2.9 on 2024-01-21 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apostilas", "0002_viewapostila"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ViewApostila",
        ),
    ]
